name: "Burndown chart generator"
description: "Generates a burndown chart for font projects based on color marks"
inputs:
  config-path:
    description: "Where the config TOML file is within the repository"
    required: true
    default: "burndown.toml"
runs:
  using: "composite"
  steps:
  - name: "Set up Python"
    uses: actions/setup-python@v2
    with:
      cache: "pip"
  - name: "Install burndown-chart-generator"
    shell: bash
    run: "pip install git+https://github.com/daltonmaag/font-burndown-chart-generator#egg=burndown-chart-generator"
  - name: "Read caching config"
    shell: bash
    run: |
      echo "Detecting if caching is enabled"
      if grep -q "^[^#]*cache *= *true" ${{ inputs.config-path }}; then
        echo "Caching is enabled"
        cache_path=$(grep -Eo '^[^#]*cache_path *= *".+"' ${{ inputs.config-path }} | grep -Eo '".+"$' | tr -d \")
        # if cache path is empty, supply default
        cache_path=${cache_path:=.burndown-chart-generator-cache.toml}
        echo "CACHE=1" >> $GITHUB_ENV
        echo "CACHE_PATH=$cache_path" >> $GITHUB_ENV
      else
        echo "Caching is disabled"
      fi
  - name: "Caching burndown stats"
    uses: actions/cache@v3
    if: ${{ env.CACHE }}
    with:
      path: env.CACHE_PATH
  - name: "Run burndown-chart-generator"
    shell: bash
    run: "burndown-chart-generator --config ${{ inputs.config-path }}"
  - name: "Export image"
    uses: actions/upload-artifact@v3
    with:
      name: "Burndown chart"
      path: "burndown-chart.png"
      if-no-files-found: error
