name: "Burndown chart generator"
description: "Generates a burndown chart for font projects based on color marks"
inputs:
  config-path:
    description: "Where the config TOML file is within the repository"
    required: true
    default: "burndown.toml"
runs:
  using: "composite"
  steps:
  - name: "Set up Python"
    uses: actions/setup-python@v4
    with:
      cache: "pip"
  - name: "Install burndown-chart-generator"
    shell: bash
    run: "pip install git+https://github.com/daltonmaag/font-burndown-chart-generator#egg=burndown-chart-generator"
  - name: "Source environment variables"
    shell: bash
    run: "burndown-chart-generator export-env --config ${{ inputs.config-path }} >> $GITHUB_ENV"
  - name: "Caching burndown stats"
    uses: actions/cache@v3
    if: env.BCG_CACHE
    with:
      path: ${{ env.BCG_CACHE_PATH }}
      key: action-burndown
  - name: "Run burndown-chart-generator"
    shell: bash
    run: |
      echo "::group::burndown-chart-generator output"
      burndown-chart-generator --config ${{ inputs.config-path }}
      echo "::endgroup::"
  - name: "Export image"
    uses: actions/upload-artifact@v3
    with:
      name: "Burndown chart"
      path: "burndown-chart.png"
      if-no-files-found: error
